networks:
  internal:
    driver: bridge

services:
  server:
    build: .
    depends_on:
      database:
        condition: service_healthy
    networks:
      - internal
    ports:
      # 8282 is the central (world) server, but we don't need to expose that. Clients interact w/ login and channel servers
      - 8484:8484 # Login server
      # - 8585-8604:8585-8604 # 8585-8604 are for Channels 1-20 on World 1, but we just use 5 channels right now
      - 8585-8589:8585-8589 # 8585-8589 are for Channels 1-5 on World 1
      # - 8685-8689:8685-8689 # 8685-8689 could be for Channels 1-5 on World 2 if we implemented multiple worlds

    volumes:
      - ./data:/kinoko/data
      - ./wz:/kinoko/wz
    environment:
      # ServerConstants
      CENTRAL_HOST: "127.0.0.1"
      CENTRAL_PORT: "8282"
      SERVER_HOST: "127.0.0.1"
      DATABASE_HOST: "database"
      # ServerConfig
      WORLD_ID: "0"
      WORLD_NAME: "Kinoko"
      CHANNEL_COUNT: "5"
      AUTO_CREATE_ACCOUNT: "true"
      REQUIRE_SECONDARY_PASSWORD: "true"
      WZ_DIRECTORY: "/kinoko/wz"
      DATA_DIRECTORY: "/kinoko/data"
      COMMAND_PREFIX: "!"
      DEBUG_MODE: "true"
  database:
    image: cassandra:5.0.0-jammy
    networks:
      - internal
    healthcheck:
      test: [ "CMD", "cqlsh", "-e", "describe keyspaces" ]
      interval: 10s
      timeout: 5s
      retries: 20
